# Generated by Django 5.2.17 on 2026-09-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_avatar_profile_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="profile",
            name="connections",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("glass", "النموذج الزجاجي"),
                    ("dark", "النموذج الداكن"),
                    ("system", "حسب الجهاز"),
                ],
                default="system",
                max_length=10,
            ),
        ),
    ]
