# Generated by Django 5.2.17 on 2026-09-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_contact_theme_connections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "فاتح"),
                    ("dark", "داكن"),
                    ("system", "حسب الجهاز"),
                    ("glass", "الزجاجي (قديم)"),
                ],
                default="system",
                max_length=10,
            ),
        ),
    ]
