# Generated by Django 5.2.17 on 2026-09-27 09:51

from django.db import migrations, models


def split_theme(apps, schema_editor):
    """القيمة القديمة بـ theme كانت نهاري/ليلي، ننقلها لـ mode، والثيم يرجع للأساسي."""
    Profile = apps.get_model('accounts', 'Profile')
    for p in Profile.objects.all():
        p.mode = p.theme if p.theme in ('light', 'dark', 'system') else 'light' if p.theme == 'glass' else 'system'
        p.theme = 'default'
        p.save(update_fields=['mode', 'theme'])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_light_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="mode",
            field=models.CharField(
                choices=[("light", "نهاري"), ("dark", "ليلي"), ("system", "تلقائي")],
                default="system",
                max_length=10,
            ),
        ),
        migrations.RunPython(split_theme, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[("default", "الأساسي")], default="default", max_length=20
            ),
        ),
    ]
