# Generated by Django 5.2.17 on 2026-09-27 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "طالب"),
                    ("faculty", "تدريسي"),
                    ("staff", "إداري"),
                ],
                default="student",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="university_id",
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name="SupportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("password", "نسيت كلمة المرور"),
                            ("support", "دعم فني"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="البريد أو الرقم الجامعي",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="وسيلة التواصل"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="الرسالة")),
                ("handled", models.BooleanField(default=False, verbose_name="تم الحل")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب مساعدة",
                "verbose_name_plural": "طلبات المساعدة",
                "ordering": ["handled", "-created_at"],
            },
        ),
    ]
