# Generated by Django 5.2.17 on 2026-09-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_authtoken_hashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hide_preview",
            field=models.BooleanField(default=False),
        ),
    ]
