# Generated by Django 5.2.17 on 2026-09-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_profile_hide_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.CharField(
                choices=[("ar", "العربية"), ("en", "English")],
                default="ar",
                max_length=5,
            ),
        ),
    ]
