# Generated by Django 5.2.17 on 2026-09-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_contacts_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="wallpaper",
            field=models.CharField(
                choices=[
                    ("doodles", "الزخارف"),
                    ("plain", "سادة"),
                    ("gradient", "متدرّجة"),
                    ("dots", "نقاط"),
                    ("campus", "صورة الكلية"),
                    ("none", "بلا خلفية"),
                ],
                default="doodles",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "البنفسجي (الأساسي)"),
                    ("green", "الأخضر"),
                    ("blue", "الأزرق"),
                    ("pink", "الوردي"),
                    ("orange", "البرتقالي"),
                    ("grey", "الرمادي"),
                ],
                default="default",
                max_length=20,
            ),
        ),
    ]
