# Generated by Django 5.2.17 on 2026-09-29 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_themes_wallpaper"),
        ("chat", "0010_conversation_settings_scheduled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="privacy_last_seen",
            field=models.CharField(
                choices=[
                    ("everyone", "الجميع"),
                    ("contacts", "جهات اتصالي"),
                    ("nobody", "لا أحد"),
                ],
                default="everyone",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="privacy_photo",
            field=models.CharField(
                choices=[
                    ("everyone", "الجميع"),
                    ("contacts", "جهات اتصالي"),
                    ("nobody", "لا أحد"),
                ],
                default="everyone",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="read_receipts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="requested_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "طالب"),
                    ("faculty", "تدريسي"),
                    ("staff", "إداري"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="two_step_hash",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="two_step_hint",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_text", models.TextField(blank=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "رسائل مزعجة"),
                            ("abuse", "محتوى مسيء"),
                            ("harassment", "تحرّش أو تهديد"),
                            ("other", "سبب آخر"),
                        ],
                        default="other",
                        max_length=12,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "handled",
                    models.BooleanField(default=False, verbose_name="تمت المراجعة"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.message",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المُبلَّغ عنه",
                    ),
                ),
            ],
            options={
                "verbose_name": "بلاغ",
                "verbose_name_plural": "البلاغات",
                "ordering": ["handled", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "حظر",
                "verbose_name_plural": "الحظر",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blocker", "blocked"), name="unique_block"
                    )
                ],
            },
        ),
    ]
