"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# كل الإعدادات الحساسة تجي من متغيرات البيئة (ملف .env بالسيرفر)، والقيم هنا للتطوير بس
def env_bool(name, default):
    return os.environ.get(name, str(default)).lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    return [x.strip() for x in os.environ.get(name, default).split(',') if x.strip()]


SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-y^i6o=t0-q12wed%@^3w-4cth*&@%!c&1&5u*4=p)g^kqnndz1')
DEBUG = env_bool('DEBUG', True)
# بالتطوير نقبل أي عنوان (حتى نفتح من الموبايل بالـ IP أو من رابط النفق)
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', '*' if DEBUG else 'localhost')
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')
# خلف Caddy/Nginx: البروكسي يگلنا إذا الطلب الأصلي كان https
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
if not DEBUG:
    SESSION_COOKIE_SECURE = CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'daphne',  # سيرفر ASGI يدعم WebSocket (لازم يكون أول شي)
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "channels",
    "accounts",
    "chat",
    "notifications",
    "stories",
    "calls",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL بالإنتاج (يتحمل آلاف الكتابات بنفس اللحظة)، وSQLite للتطوير إذا ما محدد
# مثال: DATABASE_URL=postgres://wasl:secret@db:5432/wasl
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=int(os.environ.get('DB_CONN_MAX_AGE', '60')),  # نعيد استخدام الاتصال بدل ما نفتح واحد لكل طلب
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# كلمات المرور تنحفظ بـ Argon2 (أقوى خوارزمية هاش حالياً: بطيئة عمداً وتحتاج ذاكرة، فالتخمين صعب جداً).
# الحسابات القديمة (PBKDF2) تتحول لـ Argon2 تلقائياً أول ما يسجلون دخول
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic (صفحات /admin) بالإنتاج

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---- إعدادات مشروع الشات ----

# ASGI بدل WSGI حتى نكدر نستقبل WebSocket مو بس HTTP
ASGI_APPLICATION = 'config.asgi.application'

# Channel layer: "البريد" اللي يوصل الرسائل بين اتصالات WebSocket.
# InMemory يشتغل بعملية وحدة بس (تطوير). Redis يخلي عدة عمال (workers) يوصلون لنفس الاتصالات.
REDIS_URL = os.environ.get('REDIS_URL')
if REDIS_URL:
    # Pub/Sub: أخف بكثير لما آلاف الناس متصلين (الرسالة تنبث مباشرة بدون ما تنخزن)
    CHANNEL_LAYERS = {'default': {
        'BACKEND': 'channels_redis.pubsub.RedisPubSubChannelLayer',
        'CONFIG': {'hosts': [REDIS_URL]},
    }}
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.redis.RedisCache', 'LOCATION': REDIS_URL}}
else:
    CHANNEL_LAYERS = {'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'}}

REST_FRAMEWORK = {
    # كل Request لازم يحمل Header:  Authorization: Token <token>
    # نفس Header التوكن، بس السيرفر يحفظ الهاش مالته بس (accounts/tokens.py)
    'DEFAULT_AUTHENTICATION_CLASSES': ['accounts.authentication.HashedTokenAuthentication'],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    # حماية من الإغراق: كل مستخدم (أو IP قبل الدخول) إله حد طلبات بالدقيقة.
    # العدادات بـ Redis (مشتركة بين كل العمال)
    'DEFAULT_THROTTLE_CLASSES': ['config.throttles.UserThrottle', 'config.throttles.AnonThrottle'],
    'DEFAULT_THROTTLE_RATES': {
        'user': os.environ.get('THROTTLE_USER', '600/min'),
        'anon': os.environ.get('THROTTLE_ANON', '120/min'),
        'login': os.environ.get('THROTTLE_LOGIN', '20/min'),   # تخمين كلمات المرور
        'send': os.environ.get('THROTTLE_SEND', '120/min'),    # رسائل لكل مستخدم
    },
    # خلف Caddy: عنوان المستخدم الحقيقي بـ X-Forwarded-For (وإلا الكل يطلع بعنوان البروكسي)
    'NUM_PROXIES': int(os.environ.get('NUM_PROXIES', '0')) or None,
}
THROTTLING_ENABLED = env_bool('THROTTLING_ENABLED', 'test' not in sys.argv)

# نسمح لواجهة Next.js تحچي ويا الـ API.
# بالتطوير نقبل أي بورت على جهازنا، لأن Next.js ينتقل لـ 3001 إذا 3000 محجوز.
# خلف البروكسي الواجهة والـ API بنفس العنوان فما نحتاج CORS. بالتطوير نقبل أي جهاز بالشبكة (الموبايل بالـ IP)
CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000')
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [r'^https?://(localhost|127\.0\.0\.1|10\.\d+\.\d+\.\d+|192\.168\.\d+\.\d+|172\.\d+\.\d+\.\d+)(:\d+)?$']

# الملفات اللي يرفعها المستخدمين (الصور الشخصية)
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))
# مفاتيح الإشعارات والتشفير: لازم تبقى ثابتة (بـ Docker مجلد دائم /app/keys)، وإذا ضاعت تضيع الإشعارات والرسائل المشفرة
KEYS_DIR = Path(os.environ.get('KEYS_DIR', BASE_DIR))
# أكبر ملف نقبله بالطلب (الفيديو 50 ميگا + شوية)
DATA_UPLOAD_MAX_MEMORY_SIZE = 60 * 1024 * 1024

# إشعارات Push: وسيلة تواصل وياك تنطيها لخدمات الإشعارات (Google/Apple) إذا صار مشكلة
VAPID_CONTACT = 'mailto:admin@wasl.local'

# المكالمات (WebRTC): خوادم STUN تساعد الأجهزة تلكى بعضها. بالإنتاج نضيف TURN للشبكات المقفولة
ICE_SERVERS = [{'urls': ['stun:stun.l.google.com:19302', 'stun:stun1.l.google.com:19302']}]
