# Generated by Django 5.2.17 on 2026-09-27 06:43

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_participants(apps, schema_editor):
    Conversation = apps.get_model("chat", "Conversation")
    Membership = apps.get_model("chat", "Membership")
    Message = apps.get_model("chat", "Message")
    for conv in Conversation.objects.all():
        for user in conv.participants.all():
            # كل الرسائل القديمة نعتبرها واصلة، والمقروءة منها ناخذ آخر وحدة
            last = Message.objects.filter(conversation=conv).order_by("-id").values_list("id", flat=True).first() or 0
            read = (Message.objects.filter(conversation=conv, is_read=True).exclude(sender=user)
                    .order_by("-id").values_list("id", flat=True).first() or 0)
            Membership.objects.create(conversation=conv, user=user, last_delivered_id=last, last_read_id=read)


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AddField(
            model_name="conversation",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="groups/"),
        ),
        migrations.AddField(
            model_name="conversation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="conversation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("direct", "محادثة ثنائية"),
                    ("group", "مجموعة"),
                    ("saved", "الرسائل المحفوظة"),
                ],
                default="direct",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="title",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=chat.models.message_upload_path
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="message",
            name="file_size",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "نص"),
                    ("image", "صورة"),
                    ("video", "فيديو"),
                    ("voice", "رسالة صوتية"),
                    ("file", "ملف"),
                    ("location", "موقع"),
                    ("system", "رسالة نظام"),
                ],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="live_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="chat.message",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "مشرف"), ("member", "عضو")],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("is_muted", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("last_delivered_id", models.PositiveBigIntegerField(default=0)),
                ("last_read_id", models.PositiveBigIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="chat.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        # نقل الأعضاء من الجدول القديم للجدول الجديد قبل ما نمسحه
        migrations.RunPython(copy_participants, migrations.RunPython.noop),
        migrations.RemoveField(model_name="conversation", name="participants"),
        migrations.AddField(
            model_name="conversation",
            name="participants",
            field=models.ManyToManyField(
                related_name="conversations",
                through="chat.Membership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("conversation", "user"), name="unique_membership"
            ),
        ),
    ]
