# Generated by Django 5.2.17 on 2026-09-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_groups_media_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "نص"),
                    ("image", "صورة"),
                    ("video", "فيديو"),
                    ("voice", "رسالة صوتية"),
                    ("file", "ملف"),
                    ("location", "موقع"),
                    ("system", "رسالة نظام"),
                    ("call", "مكالمة"),
                ],
                default="text",
                max_length=10,
            ),
        ),
    ]
