# Generated by Django 5.2.17 on 2026-09-28 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_pin_clear_reactions_stars"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["conversation", "-id"], name="msg_conv_id_desc"),
        ),
    ]
