# Generated by Django 5.2.17 on 2026-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_encrypt_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("direct", "محادثة ثنائية"),
                    ("group", "مجموعة"),
                    ("saved", "الرسائل المحفوظة"),
                    ("channel", "قناة"),
                ],
                default="direct",
                max_length=10,
            ),
        ),
    ]
