# Generated by Django 5.2.17 on 2026-09-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_existing_chats_become_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
